[package]
name    = "yo-esp"
version = "0.1.7"
edition = "2024"

description = """
    yo-esp is a bare‑metal, no_std audio streaming client for the yo voice assistant. It provides everything needed to capture microphone audio, stream it to a backend server, receive and play back TTS/audio, and react to server‑side wake‑word detection, speech‑to‑text, intent recognition and command execution.""" 

authors    = ["QuackHack-McBlindy"]
repository = "https://github.com/QuackHack-McBlindy/yo-esp"
license    = "MIT"
readme     = "README.md"
keywords   = [ "no-std", "esp-hal", "embedded", "i2s", "audio", "esp32s3", "embassy", "esp32"]
categories = [
    "embedded",
    "no-std",
    "development-tools",
    "network-programming"
]

[lib]
crate-type = ["lib"]

[dependencies]
esp-hal = { version = "1.1.0", features = ["esp32s3", "unstable"] }
embassy-net = { version = "0.9.0", features = ["tcp", "proto-ipv4", "medium-ethernet"] }
embassy-time = "0.5.0"
embassy-futures = "0.1.0"
embassy-sync = "0.8.0"
embassy-executor = "0.10.0"
libm = "0.2" 
defmt = "1.0.0"

[features]
sounds = []
